% Hechos: Relaciones en el árbol genealógico
% Indicar genero de cada integrante 

%Hombres
hombre(tenji).
%--------------
hombre(hagoromo).
hombre(hamura).
hombre(zetsu).
hombre(indra).
hombre(ashura).
%-------------
hombre(tajima).
hombre(madara).
hombre(izuna).
%-------------
hombre(ashina).
hombre(butsuma).
hombre(hashirama).
hombre(tobirama).
%-------------
hombre(tsunadePadre).
hombre(nawaki).
hombre(dan).
%-------------
hombre(shizui).
hombre(shizuiPadre).
%-------------
hombre(itachi).
hombre(sasuke).
hombre(fugaku).
hombre(teyaki).
hombre(fugakuPadre).
%-------------
hombre(kizashi).
%-------------
hombre(obitoPadre).
hombre(obito).
%-------------
hombre(minato).
hombre(naruto).
hombre(boruto).
%-------------
hombre(neji).
hombre(hiashi).
hombre(hizashi).
hombre(hideki).


%Mujeres
mujer(sarada).
mujer(sakura).
mujer(mikoto).
mujer(uruchi).
mujer(mebuki).
%--------------
mujer(izumi).
mujer(hazuki).
%--------------
mujer(himawari).
mujer(kushina).
%--------------
mujer(tsunade).
mujer(biwako).
%--------------
mujer(hinata).
mujer(hanabi).
%--------------
mujer(mito).
%--------------
mujer(kaguya).

% Indicar quien es el «progenitor» de alguien mas
progenitor(kaguya,zetsu).
progenitor(kaguya,hagoromo).
progenitor(kaguya,hamura).
%-------------------------
progenitor(hagoromo,indra).
progenitor(hagoromo,ashura).
%-------------------------
progenitor(tajima,madara).
progenitor(tajima,izuna).
%-------------------------
progenitor(hazuki,izumi).
%-------------------------
progenitor(shizuiPadre,shizui).
%-------------------------
progenitor(obitoPadre,obito).
progenitor(fugakuPadre,fugaku).
progenitor(fugakuPadre,teyaki).
%-------------------------
progenitor(mikoto,itachi).
progenitor(mikoto,sasuke).
progenitor(fugaku,itachi).
progenitor(fugaku,sasuke).
%-------------------------
progenitor(kizashi,sakura).
progenitor(mebuki,sakura).
%-------------------------
progenitor(sakura,sarada).
progenitor(sasuke,sarada).
%-------------------------
progenitor(hamura,hideki).
progenitor(hideki,hiashi).
progenitor(hideki,hizashi).
progenitor(hizashi,neji).
progenitor(hiashi,hinata).
progenitor(hiashi,hanabi).
%------------------------
progenitor(hinata,himawari).
progenitor(hinata,boruto).
progenitor(naruto,himawari).
progenitor(naruto,boruto).
%------------------------
progenitor(minato,naruto).
progenitor(kushina,naruto).
%------------------------
progenitor(butsuma,hashirama).
progenitor(butsuma,tobirama).
%------------------------
progenitor(ashina,mito).
%------------------------
progenitor(hashirama,biwako).
progenitor(mito,biwako).
progenitor(biwako,tsunade).
progenitor(tsunadePadre,tsunade).
progenitor(biwako,nawaki).
progenitor(tsunadePadre,nawaki).

%Indicar quien es pareja de quien
pareja(itachi,izumi).
pareja(izumi, itachi).
pareja(mikoto,fugaku).
pareja(fugaku, mikoto).
pareja(teyaki,uruchi).
pareja(uruchi,teyaki).
pareja(sasuke,sakura).
pareja(sakura,sasuke).
pareja(boruto,sarada).
pareja(sarada,boruto).
pareja(naruto,hinata).
pareja(hinata,naruto).
pareja(kushina,minato).
pareja(minato,kushina).
pareja(tsunade,dan).
pareja(dan,tsunade).
pareja(biwako,tsunadePadre).
pareja(tsunadePadre,biwako).
pareja(mito,hashirama).
pareja(hashirama,mito).
pareja(tenji,kaguya).
pareja(kaguya,tenji).


% Generar reglas
padre(X,Y):-hombre(X),progenitor(X,Y).
madre(X,Y):-mujer(X),progenitor(X,Y).
hermanos(X,Y):-progenitor(Z,X),progenitor(Z,Y), not(X==Y).
hermano(X,Y):-hombre(X),hermanos(X,Y).
hermana(X,Y):-mujer(X),hermanos(X,Y).
esposo(X,Y):-pareja(X,Y),hombre(X).
esposa(X,Y):-pareja(X,Y),mujer(X).
suegro(X,Y):-padre(X,Z),pareja(Y,Z).
suegra(X,Y):-madre(X,Z),pareja(Y,Z).
yerno(X,Y):-suegro(Y,X);suegra(Y,X),hombre(X).
nuera(X,Y):-suegro(Y,X);suegra(Y,X),mujer(X).
cunados(X,Z):-pareja(X,Y),hermanos(Y,Z);pareja(Z,Y), hermanos(Y,X).
cunnado(X,Y):-cunados(X,Y),hombre(X).
cunada(X,Y):-cunados(X,Y),mujer(X).
abuelo(X,Y):-progenitor(Z,Y),padre(X,Z).
abuela(X,Y):-progenitor(Z,Y),madre(X,Z).
nieto(X,Y):-progenitor(Y,Z),progenitor(Z,X),hombre(X).
nieta(X,Y):-progenitor(Y,Z),progenitor(Z,X),mujer(X).
tio(X,Y):-progenitor(Z,Y),(hermano(X,Z);cunnado(X,Z)).
tia(X,Y):-progenitor(Z,Y),(hermana(X,Z);cunada(X,Z)).
primo(X,Y):-progenitor(Z,X),progenitor(W,Y),hermanos(Z,W),hombre(X).
prima(X,Y):-progenitor(Z,X),progenitor(W,Y),hermanos(Z,W),mujer(X).